name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Build package
        run: uv build

      - name: Perform import test (wheel)
        run: uv run --isolated --no-project -p 3.13 --with dist/*.whl -- python -c "from timecopilot import TimeCopilot"

      - name: Perform import test (source distribution)
        run: uv run --isolated --no-project -p 3.13 --with dist/*.tar.gz -- python -c "from timecopilot import TimeCopilot"

      - name: Publish package
        run: uv publish --trusted-publishing always

      - name: After publishing test
        run: uv run --isolated --no-project -p 3.13 --with timecopilot -- python -c "from timecopilot import TimeCopilot"

  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare env
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          echo "CHANGELOG_FILE=docs/changelogs/${GITHUB_REF_NAME}.md" >> "$GITHUB_ENV"

      - name: Read changelog
        id: changelog
        env:
          FILE: ${{ env.CHANGELOG_FILE }}
        run: |
          if [[ -f "$FILE" ]]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
            CONTENT="$(python - <<'PY'
              import sys, urllib.parse
              print(urllib.parse.quote(sys.stdin.read()))
              PY
            < "$FILE")"
            echo "body=${CONTENT}" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
            echo "body=" >> "$GITHUB_OUTPUT"
          fi

      - name: Notify Discord
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: TimeCopilot Releases
          severity: info
          title: "🚀 New release ${{ env.TAG }}"
          description: "Changelog also available at https://timecopilot.dev/changelogs/${{ env.TAG }}/"
          details: ${{ steps.changelog.outputs.body }}
          processingOptions: percentDecode
          footer: "pushed via GitHub Actions"
